## docker-compose para correr wordpress con una base de datos en mysql
## by PeladoNerd 2018
## modified danielroj 2021

version: '3.8'

services:

  wordpress:
    image: wordpress:5.7.2-php7.4-apache
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    links:
      - mysql:mysql


  mysql:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ~/Documents/DATA_DOCKER:/var/lib/mysql

